# Site settings
title: Ban Lam De Thuong - Web Developer
description: "Chuyen mod file SF3 BNSVN ..."
baseurl: "banlamdethuong.github.io"
url: "banlamdethuong.github.io"

# User settings
username: Ban Lam De Thuong
user_title: banlamdethuong
email: imhereifyouwant@gmail.com
twitter_username: 
github_username:  
gplus_username:  
linkedin_public_url: 
disqus_username: 
profile_picture:
